"""initial_schema

Revision ID: abbe683d138f
Revises: 
Create Date: 2026-08-06 12:08:27.612708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbe683d138f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_works',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('normalized_title', sa.String(length=1000), nullable=False),
    sa.Column('journal', sa.String(length=500), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attention_evidence',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('work_id', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('matched_identifier', sa.String(length=500), nullable=False),
    sa.Column('match_confidence', sa.String(length=50), nullable=False),
    sa.Column('raw_reference_json', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['research_works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'source', 'external_id', name='uq_evidence_work_source_ext_id'),
    sa.UniqueConstraint('work_id', 'source', 'url_hash', name='uq_evidence_work_source_url_hash')
    )
    op.create_index('idx_evidence_source_date', 'attention_evidence', ['source', 'discovered_at'], unique=False)
    op.create_table('attention_jobs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('work_id', sa.String(length=50), nullable=False),
    sa.Column('job_kind', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('error_details', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['research_works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_refreshes',
    sa.Column('work_id', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('next_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['research_works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_id', 'source')
    )
    op.create_table('work_identifiers',
    sa.Column('work_id', sa.String(length=50), nullable=False),
    sa.Column('scheme', sa.String(length=50), nullable=False),
    sa.Column('normalized_value', sa.String(length=500), nullable=False),
    sa.Column('display_value', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['research_works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_id', 'scheme', 'normalized_value'),
    sa.UniqueConstraint('scheme', 'normalized_value', name='uq_identifiers_scheme_value')
    )
    op.create_index('idx_identifiers_lookup', 'work_identifiers', ['scheme', 'normalized_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_identifiers_lookup', table_name='work_identifiers')
    op.drop_table('work_identifiers')
    op.drop_table('source_refreshes')
    op.drop_table('attention_jobs')
    op.drop_index('idx_evidence_source_date', table_name='attention_evidence')
    op.drop_table('attention_evidence')
    op.drop_table('research_works')
    # ### end Alembic commands ###
